//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserva
    {
        public int idReserva { get; set; }
        public System.DateTime fecha { get; set; }
        public int idActividad { get; set; }
        public string nombreCliente { get; set; }
        public string numeroContactoCliente { get; set; }
        public byte cantidadPersonas { get; set; }
        public decimal total { get; set; }
        public int idUsuario { get; set; }
    
        public virtual actividad actividad { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
